version: '3.9'

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -I -w '%{http_code}' http://localhost:8000 | grep -q 400"]
      interval: 10s
      timeout: 10s
      retries: 10

  aws-cli:
    depends_on:
      dynamodb:
        condition: service_healthy 
    image: amazon/aws-cli
    volumes:
      - "./schemas:/tmp/dynamo"
    environment:
      AWS_ACCESS_KEY_ID: 'fake'
      AWS_SECRET_ACCESS_KEY: 'fake'
      AWS_REGION: 'us-east-1'
    command: >
      dynamodb create-table 
      --endpoint-url http://dynamodb:8000
      --table-name order_payment 
      --attribute-definitions AttributeName=order_id,AttributeType=N 
      --key-schema AttributeName=order_id,KeyType=HASH 
      --billing-mode PAY_PER_REQUEST

  api:
    depends_on:
      dynamodb:
        condition: service_healthy 
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    ports:
      - "8080:8080"
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge